### ISSUE TITLE
I can't register to Nertivia :(

### ISSUE THREAD

**Issue by kacperr5** [Nertivia/legacy-nertivia-client#302]
**Device + OS:**
MacBook + macOS

**Browser:**
Safari
**Bug:**
I can't register. Look to screenshot
<img width="506" alt="Screenshot 2021-08-06 at 16 36 37" src="https://user-images.githubusercontent.com/76687465/128527648-98776fc0-8529-488a-a175-9f6ac668f30d.png">

**Comment by supertiger1234** [comment]
Thanks for letting me know. It should be fixed now!
