### ISSUE TITLE
Color/variables settings for themes

### ISSUE THREAD

**Issue by atomic-addison** [Nertivia/Legacy-Nertivia-Client#47]
Would be nice if users had access to theme variables in the settings. For example, the user can click on a cog icon next to an installed theme and JS will pick up all the css variables (if any) from the theme's :root element and let the user set the values, creating a cached set of :root variables that will just replace the theme's default onload

**Comment by supertiger1234** [comment]
Ahh I better understand what you mean now. This would be epic.

**Comment by FluxedScript** [comment]
I like this too

**Comment by Brecert** [comment]
This has been added in the new client.
