### ISSUE TITLE
Example of config.js? 

### ISSUE THREAD

**Issue by byte1080** [Nertivia/Legacy-Nertivia-Client#71]
Hello, I don't seem to see an example of a config.js anywhere, I'm planning to test this out locally, and use it internally aka as a private chat server.

**Comment by supertiger1234** [comment]
There's an config template kind of in the Interface folder. I will provide a proper template maybe later today.

**Comment by supertiger1234** [comment]
Nevermind! That's for the server.

**Comment by byte1080** [comment]
Alright, with the server, does it automatically run database migrations/database imports when you first run the sevrer? I can't seem to find any empty SQL files in the server folder.

**Comment by byte1080** [comment]
server*

**Comment by supertiger1234** [comment]
Its not SQL, its mongodb. mongodb creates all the stuff automatically.

**Comment by byte1080** [comment]
ah, alright

**Comment by Brecert** [comment]
The client config file should look something like, although there might be properties or settings I'm missing.

```
const config = {
  // if you're in development mode
  devMode: true,

  // the nertivia domain name
  domain: "https://supertiger.tk/api",

  // the socket ip (lol)
  socketIP: "https://nertivia.supertiger.tk"

  // the uri to the nertivia cdn
  nertiviaCDN: "https://media.nertivia.tk"
}

export default config
```

**Comment by Brecert** [comment]
The [new client](https://github.com/supertiger1234/nertivia-client-ts) has an example.env
