### ISSUE TITLE
Link Changes

### ISSUE THREAD

**Issue by Jared-Galyan** [Nertivia/Legacy-Nertivia-Client#73]
Instead of always having the link `https://nertivia.supertiger.tk/app` change it to more like `nertivia.tk/guild_id/channel_id` that would allow users to jump right back to where they left off if they refresh the page and whatnot

**Comment by supertiger1234** [comment]
attempted this, i found it hard doing this, im gonna try this some other time again.

**Comment by Brecert** [comment]
This feature was added in the [new client](https://github.com/supertiger1234/nertivia-client-ts).
