### ISSUE TITLE
Server staying on the list even though I've left

### ISSUE THREAD

**Issue by ghost** [Nertivia/Legacy-Nertivia-Client#80]
**Device + OS:**
Windows

**Browser:**
Google Chrome

**Bug:**
I was testing something, spamming leave/join requests on a target server to see how it'd affect the API, sometimes, the server would stay there on the server list with all of its channels, but nothing would load and when I try chat in it, I'd get the message of "Channel does not exist." and/or failed to send message.

**Comment by supertiger1234** [comment]
This will be hard to reproduce ;-;

**Comment by Brecert** [comment]
With the [new client](https://github.com/supertiger1234/nertivia-client-ts) this should hopefully be fixed.
